### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
import numpy as np

In [60]:
N = 10
m = np.arange(10, 0, -1)-1
m

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [61]:
np.diag(m).sum()

45

### Задание 3
Решите систему уравнений:
4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [64]:
from numpy import linalg

In [62]:
a = np.array(
    [
        [4, 2, 1],
        [1, 3, 0],
        [0, 5, 4]
    ]
)
b = np.array([4, 12, -3])

In [65]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [66]:
# проверка 

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

### Задача 4 домашнего задания

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [75]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ]
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [73]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength)

In [105]:
# список значений косинусного расстояния для всех пользователей статитситки
next_user_alike = np.array([cosine(user, next_user_stats) for user in users_stats])

# пользователь, который наиболее похож на нового юзера
users_stats[next_user_alike.argmax()]

array([0, 1, 1, 0, 0, 0])